on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - run: npm run build

      - run: npm test

      - run: |
          npm run codegen
          if ! git diff --exit-code; then
            echo "Error: Found uncommitted changes after running 'npm run codegen'"
            echo "Please run 'npm run codegen' locally and commit the changes"
            git diff
            exit 1
          fi
