on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - run: npm run build

      - run: npm test

      - run: |
          npm run codegen
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Found uncommitted changes after running 'npm run codegen'"
            echo "Please run 'npm run codegen' locally and commit the changes"
            echo ""
            echo "=== Git Status ==="
            git status
            echo ""
            echo "=== Changes to existing files ==="
            git diff
            echo ""
            echo "=== New untracked files ==="
            git ls-files --others --exclude-standard | head -20
            if [ $(git ls-files --others --exclude-standard | wc -l) -gt 20 ]; then
              echo "... and $(( $(git ls-files --others --exclude-standard | wc -l) - 20 )) more files"
            fi
            exit 1
          fi
